#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
//CONCEPT_DLL_API ON_CREATE_CONTEXT MANAGEMENT_PARAMETERS;
//CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_DLL_API CONCEPT_NewTemplateContext CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_TBind    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_TUnBind  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_TCompile CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_TErrors  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_TExecute CONCEPT_API_PARAMETERS;

CONCEPT_DLL_API CONCEPT_DestroyTemplateContext CONCEPT_API_PARAMETERS;
}
#endif // __LIBRARY_H
