#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API CONCEPT__memchr    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__memcmp    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__memcpy    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__memmove   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__memset    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strcat    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strchr    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strcmp    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strcoll   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strcpy    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strcspn   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT___strerror CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strlen    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strncat   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strncmp   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strncpy   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strpbrk   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strrchr   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strspn    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strstr    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strtok    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__strxfrm   CONCEPT_API_PARAMETERS;
}
#endif // __LIBRARY_H
