#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;


// other functions declared here
CONCEPT_DLL_API CONCEPT_SerializeObject   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_UnSerializeObject CONCEPT_API_PARAMETERS;

CONCEPT_DLL_API CONCEPT_HasMember    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_SetMember    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_GetMember    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_CreateObject CONCEPT_API_PARAMETERS;

CONCEPT_DLL_API CONCEPT_ObjectLinks CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_StaticLinks CONCEPT_API_PARAMETERS;

CONCEPT_DLL_API CONCEPT__ASSERT CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__ClsPtr CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__VarPtr CONCEPT_API_PARAMETERS;

CONCEPT_DLL_API CONCEPT__KeySorted CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__IsSet     CONCEPT_API_PARAMETERS;

CONCEPT_DLL_API CONCEPT__GetKeys CONCEPT_API_PARAMETERS;

CONCEPT_FUNCTION(SerializeError)

CONCEPT_FUNCTION(ToXML)
CONCEPT_FUNCTION(ToArray)
CONCEPT_FUNCTION(FromXML)

CONCEPT_FUNCTION(BinarizeObject)
CONCEPT_FUNCTION(UnBinarizeObject)
CONCEPT_FUNCTION(ToSize)
CONCEPT_FUNCTION(FromSize)
CONCEPT_FUNCTION(CreateObject2)
CONCEPT_FUNCTION(pack)
CONCEPT_FUNCTION(unpack)

CONCEPT_FUNCTION(compress)
CONCEPT_FUNCTION(uncompress)

CONCEPT_FUNCTION(__callstack)
CONCEPT_FUNCTION(__object)

CONCEPT_FUNCTION(hpack)
CONCEPT_FUNCTION(hunpack)
}
#endif // __LIBRARY_H
