#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT MANAGEMENT_PARAMETERS;

// other functions declared here
CONCEPT_DLL_API CONCEPT__abs   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__acos  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__asin  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__atan  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__ceil  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__cos   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__exp   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__fabs  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__floor CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__fmod  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__labs  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__ldexp CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__log   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__log10 CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__pow   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__rand  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__sin   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__sqrt  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__srand CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__tan   CONCEPT_API_PARAMETERS;

CONCEPT_FUNCTION(_round)
CONCEPT_FUNCTION(_number_format)
CONCEPT_FUNCTION(FFT)
CONCEPT_FUNCTION(Mix)
CONCEPT_FUNCTION(PCMAvg)
CONCEPT_FUNCTION(PCMAmplify)
}
#endif // __LIBRARY_H
