#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
    CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
    CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

    CONCEPT_FUNCTION(JSNewRuntime)
    CONCEPT_FUNCTION(JSDestroyRuntime)
    CONCEPT_FUNCTION(JSEvaluateScript)
    CONCEPT_FUNCTION(JSEvaluateFile)
    CONCEPT_FUNCTION(JSCall)
    CONCEPT_FUNCTION(JSWrap)
    CONCEPT_FUNCTION(JSVariable)
    CONCEPT_FUNCTION(JSThrow)
    CONCEPT_FUNCTION(JSErrorCode)
    CONCEPT_FUNCTION(JSGC)
    CONCEPT_FUNCTION(JSModeBinary)
    CONCEPT_FUNCTION(JSTimeout)
}
#endif // __LIBRARY_H
