#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(iconv_open)
CONCEPT_FUNCTION(iconv_close)
CONCEPT_FUNCTION(iconv)
CONCEPT_FUNCTION(iconv2)
CONCEPT_FUNCTION(iconvctl)
}
#endif // __LIBRARY_H
