#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
// other functions declared here
CONCEPT_DLL_API CONCEPT__int8   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__int16  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__int32  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__int64  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__uint8  CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__uint16 CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__uint32 CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__uint64 CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__float  CONCEPT_API_PARAMETERS;

CONCEPT_FUNCTION(_tobin)
CONCEPT_FUNCTION(_tonumber)
CONCEPT_FUNCTION(_toubin)
CONCEPT_FUNCTION(_tounumber)

CONCEPT_FUNCTION(CreateStaticArray)
CONCEPT_FUNCTION(FreeStaticArray)
CONCEPT_FUNCTION(GetStaticArray)
CONCEPT_FUNCTION(SetStaticArray)
CONCEPT_FUNCTION(FillStaticArray)
}
#endif // __LIBRARY_H
