#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(CSVCreate)
CONCEPT_FUNCTION(CSVDone)
CONCEPT_FUNCTION(CSVParse)
CONCEPT_FUNCTION(CSVError)
CONCEPT_FUNCTION(CSVErrorExplain)
CONCEPT_FUNCTION(CSVSetDelim)
CONCEPT_FUNCTION(CSVSetQuote)
}
#endif // __LIBRARY_H
