#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
    CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
    CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

    CONCEPT_FUNCTION(MsSpeech_Create)
    CONCEPT_FUNCTION(MsSpeech_Free)

    CONCEPT_FUNCTION(MsSpeech_FeedAudioContent)

    CONCEPT_FUNCTION(MsSpeech_Reset)
    CONCEPT_FUNCTION(MsSpeech_Decode)

    CONCEPT_FUNCTION(MsSpeech_TTS)
}
#endif // __LIBRARY_H
