#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(VRConfInit)
CONCEPT_FUNCTION(VRConfDone)

CONCEPT_FUNCTION(VRInit)
CONCEPT_FUNCTION(VRStart)
CONCEPT_FUNCTION(VRAddBuffer)
CONCEPT_FUNCTION(VREnd)
CONCEPT_FUNCTION(VRResult);
CONCEPT_FUNCTION(VRDone)
}
#endif // __LIBRARY_H
