#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API CONCEPT_CLArg      CONCEPT_API_PARAMETERS;

CONCEPT_FUNCTION(GLOBALS)
CONCEPT_FUNCTION(eval)
CONCEPT_FUNCTION(IncludeCode)
CONCEPT_FUNCTION(RemoveClass)
CONCEPT_FUNCTION(CheckReachability)
}
#endif // __LIBRARY_H
