#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(MapOpen)
CONCEPT_FUNCTION(MapClose)
CONCEPT_FUNCTION(MapPut)
CONCEPT_FUNCTION(MapPutMultiple)
CONCEPT_FUNCTION(MapGet)
CONCEPT_FUNCTION(MapGetNumber)
CONCEPT_FUNCTION(MapGetInt)
CONCEPT_FUNCTION(MapRemove)
CONCEPT_FUNCTION(MapRemoveValue)
CONCEPT_FUNCTION(MapError)
CONCEPT_FUNCTION(MapInfo)
CONCEPT_FUNCTION(MapGetAll)
CONCEPT_FUNCTION(MapGetAllNumber)
CONCEPT_FUNCTION(MapGetAllNumberMI)
CONCEPT_FUNCTION(MapDrop)
CONCEPT_FUNCTION(MapCount)
}
#endif // __LIBRARY_H
