#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
    CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
    CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

    CONCEPT_FUNCTION(TLSEServer)
    CONCEPT_FUNCTION(TLSEClient)
    CONCEPT_FUNCTION(TLSEDone)
    CONCEPT_FUNCTION(TLSEAccept)
    CONCEPT_FUNCTION(TLSERequestClientCertificate)
    CONCEPT_FUNCTION(TLSERead)
    CONCEPT_FUNCTION(TLSEWrite)
    CONCEPT_FUNCTION(TLSEConsume)
    CONCEPT_FUNCTION(TLSEstablished)
    CONCEPT_FUNCTION(TLSEPending)
    CONCEPT_FUNCTION(TLSESent)
    CONCEPT_FUNCTION(TLSELoadKeys)
    CONCEPT_FUNCTION(TLSELoadRootCA)
    CONCEPT_FUNCTION(TLSEChipher)
    CONCEPT_FUNCTION(TLSEChipherName)
    CONCEPT_FUNCTION(TLSEBroken)
    CONCEPT_FUNCTION(TLSESetExportable)
    CONCEPT_FUNCTION(TLSEExport)
    CONCEPT_FUNCTION(TLSEImport)
    CONCEPT_FUNCTION(TLSGetSNI)
    CONCEPT_FUNCTION(TLSSetSNI)
    CONCEPT_FUNCTION(TLSSetVerify)
}
#endif // __LIBRARY_H
