#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
    CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
    CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

    CONCEPT_FUNCTION(TLSEServer)
    CONCEPT_FUNCTION(TLSEClient)
    CONCEPT_FUNCTION(TLSEDone)
    CONCEPT_FUNCTION(TLSEAccept)
    CONCEPT_FUNCTION(TLSEConnect)
    CONCEPT_FUNCTION(TLSERequestClientCertificate)
    CONCEPT_FUNCTION(TLSERead)
    CONCEPT_FUNCTION(TLSEWrite)
    CONCEPT_FUNCTION(TLSEConsume)
    CONCEPT_FUNCTION(TLSEstablished)
    CONCEPT_FUNCTION(TLSEPending)
    CONCEPT_FUNCTION(TLSEReadBufferSize)
    CONCEPT_FUNCTION(TLSESent)
    CONCEPT_FUNCTION(TLSELoadKeys)
    CONCEPT_FUNCTION(TLSELoadRootCA)
    CONCEPT_FUNCTION(TLSEChipher)
    CONCEPT_FUNCTION(TLSEChipherName)
    CONCEPT_FUNCTION(TLSEBroken)
    CONCEPT_FUNCTION(TLSESetExportable)
    CONCEPT_FUNCTION(TLSEExport)
    CONCEPT_FUNCTION(TLSEImport)
    CONCEPT_FUNCTION(TLSEGetSNI)
    CONCEPT_FUNCTION(TLSESetSNI)
    CONCEPT_FUNCTION(TLSESetVerify)
    CONCEPT_FUNCTION(TLSECertificateInfo)
    CONCEPT_FUNCTION(TLSEShutdown)
    CONCEPT_FUNCTION(TLSEError)
    CONCEPT_FUNCTION(TLSEAddALPN)
    CONCEPT_FUNCTION(TLSEALPN)
    CONCEPT_FUNCTION(TLSEClearCertificates)

    CONCEPT_FUNCTION(SRTPInit)
    CONCEPT_FUNCTION(SRTPEncrypt)
    CONCEPT_FUNCTION(SRTPDecrypt)
    CONCEPT_FUNCTION(SRTPDone)

    CONCEPT_FUNCTION(RTCPeerConnectionInit)
    CONCEPT_FUNCTION(RTCPeerConnectionConnect)
    CONCEPT_FUNCTION(RTCPeerConnectionInfo)
    CONCEPT_FUNCTION(RTCPeerConnectionStatus)
    CONCEPT_FUNCTION(RTCPeerConnectionRemoteCredentials)
    CONCEPT_FUNCTION(RTCPeerConnectionClone)
    CONCEPT_FUNCTION(RTCPeerConnectionConsume)
    CONCEPT_FUNCTION(RTCPeerConnectionDone)
    CONCEPT_FUNCTION(RTCPeerConnectionGetWriteBuffer)
    CONCEPT_FUNCTION(RTCPeerConnectionGetReadBuffer)
    CONCEPT_FUNCTION(RTCPeerConnectionEncrypt)
    CONCEPT_FUNCTION(RTCPeerConnectionDecrypt)
}
#endif // __LIBRARY_H
