#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
    CONCEPT_DLL_API ON_CREATE_CONTEXT MANAGEMENT_PARAMETERS;
    CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

    CONCEPT_FUNCTION(PollOpen)
    CONCEPT_FUNCTION(PollAdd)
    CONCEPT_FUNCTION(PollUpdate)
    CONCEPT_FUNCTION(PollRemove)
    CONCEPT_FUNCTION(PollWait)
    CONCEPT_FUNCTION(PollClose)
}
#endif // __LIBRARY_H
