#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(H264Encoder)
CONCEPT_FUNCTION(H264Decoder)
CONCEPT_FUNCTION(H264EncoderSet)
CONCEPT_FUNCTION(H264DecoderSet)
CONCEPT_FUNCTION(H264EncoderGet)
CONCEPT_FUNCTION(H264DecoderGet)
CONCEPT_FUNCTION(H264Encode)
CONCEPT_FUNCTION(H264Decode)
CONCEPT_FUNCTION(H264EncoderDone)
CONCEPT_FUNCTION(H264DecoderDone)

CONCEPT_FUNCTION(YUV420Overlay)
}
#endif // __LIBRARY_H
