/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.net)
	con.net = { };
con.net.RTPCreate = this.__cjs_RTPCreate;
con.net.RTPError = this.__cjs_RTPError;
con.net.RTPBYEDestroy = this.__cjs_RTPBYEDestroy;
con.net.RTPDestroy = this.__cjs_RTPDestroy;
con.net.RTPAddDestination = this.__cjs_RTPAddDestination;
con.net.RTPDeleteDestination = this.__cjs_RTPDeleteDestination;
con.net.RTPClearDestinations = this.__cjs_RTPClearDestinations;
con.net.RTPSend = this.__cjs_RTPSend;
con.net.RTPBeginDataAccess = this.__cjs_RTPBeginDataAccess;
con.net.RTPEndDataAccess = this.__cjs_RTPEndDataAccess;
con.net.RTPGetNextPacket = this.__cjs_RTPGetNextPacket;
con.net.RTPGotoFirstSourceWithData = this.__cjs_RTPGotoFirstSourceWithData;
con.net.RTPGotoNextSourceWithData = this.__cjs_RTPGotoNextSourceWithData;
con.net.RTPGotoPreviousSourceWithData = this.__cjs_RTPGotoPreviousSourceWithData;
con.net.RTPGetCurrentSourceInfo = this.__cjs_RTPGetCurrentSourceInfo;
con.net.RTPCurrentSourceReceivedBYE = this.__cjs_RTPCurrentSourceReceivedBYE;
con.net.RTPPoll = this.__cjs_RTPPoll;
con.net.RTPSetDefaultPayloadType = this.__cjs_RTPSetDefaultPayloadType;
con.net.RTPSetDefaultMark = this.__cjs_RTPSetDefaultMark;
con.net.RTPSetDefaultTimestampIncrement = this.__cjs_RTPSetDefaultTimestampIncrement;
con.net.RTPIncrementTimestamp = this.__cjs_RTPIncrementTimestamp;
con.net.RTPIncrementTimestampDefault = this.__cjs_RTPIncrementTimestampDefault;
con.net.RTPSetPreTransmissionDelay = this.__cjs_RTPSetPreTransmissionDelay;
con.net.RTPSetReceiveMode = this.__cjs_RTPSetReceiveMode;
con.net.RTPAddToIgnoreList = this.__cjs_RTPAddToIgnoreList;
con.net.RTPDeleteFromIgnoreList = this.__cjs_RTPDeleteFromIgnoreList;
con.net.RTPClearIgnoreList = this.__cjs_RTPClearIgnoreList;
con.net.RTPAddToAcceptList = this.__cjs_RTPAddToAcceptList;
con.net.RTPDeleteFromAcceptList = this.__cjs_RTPDeleteFromAcceptList;
con.net.RTPSetMaximumPacketSize = this.__cjs_RTPSetMaximumPacketSize;
con.net.RTPSetSessionBandwidth = this.__cjs_RTPSetSessionBandwidth;
con.net.RTPSetTimestampUnit = this.__cjs_RTPSetTimestampUnit;
con.net.RTPSetNameInterval = this.__cjs_RTPSetNameInterval;
con.net.RTPSetEMailInterval = this.__cjs_RTPSetEMailInterval;
con.net.RTPSetLocationInterval = this.__cjs_RTPSetLocationInterval;
con.net.RTPSetPhoneInterval = this.__cjs_RTPSetPhoneInterval;
con.net.RTPSetToolInterval = this.__cjs_RTPSetToolInterval;
con.net.RTPSetNoteInterval = this.__cjs_RTPSetNoteInterval;
con.net.RTPSetLocalName = this.__cjs_RTPSetLocalName;
con.net.RTPSetLocalEMail = this.__cjs_RTPSetLocalEMail;
con.net.RTPSetLocalLocation = this.__cjs_RTPSetLocalLocation;
con.net.RTPSetLocalPhone = this.__cjs_RTPSetLocalPhone;
con.net.RTPSetLocalTool = this.__cjs_RTPSetLocalTool;
con.net.RTPSetLocalNote = this.__cjs_RTPSetLocalNote;
con.net.RTPWait = this.__cjs_RTPWait;
