/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.lib)
	con.lib = { };
con.lib.virError = this.__cjs_virError;
con.lib.virConnect = this.__cjs_virConnect;
con.lib.virInfo = this.__cjs_virInfo;
con.lib.virClose = this.__cjs_virClose;
con.lib.virNumOfActiveDomains = this.__cjs_virNumOfActiveDomains;
con.lib.virNumOfInactiveDomains = this.__cjs_virNumOfInactiveDomains;
con.lib.virListAllDomains = this.__cjs_virListAllDomains;
con.lib.virDomainOpen = this.__cjs_virDomainOpen;
con.lib.virDomainOpenUUID = this.__cjs_virDomainOpenUUID;
con.lib.virDomainOpenName = this.__cjs_virDomainOpenName;
con.lib.virDomainDone = this.__cjs_virDomainDone;
con.lib.virDomainMemoryPeek = this.__cjs_virDomainMemoryPeek;
con.lib.virDomainShutdown = this.__cjs_virDomainShutdown;
con.lib.virDomainSetAutostart = this.__cjs_virDomainSetAutostart;
con.lib.virDomainDestroy = this.__cjs_virDomainDestroy;
con.lib.virDomainSuspend = this.__cjs_virDomainSuspend;
con.lib.virDomainResume = this.__cjs_virDomainResume;
con.lib.virDomainUndefine = this.__cjs_virDomainUndefine;
con.lib.virDomainCreate = this.__cjs_virDomainCreate;
con.lib.virDomainCreateXML = this.__cjs_virDomainCreateXML;
con.lib.virDomainScreenshot = this.__cjs_virDomainScreenshot;
con.lib.virDomainSendKey = this.__cjs_virDomainSendKey;
con.lib.virDomainOpenConsole = this.__cjs_virDomainOpenConsole;
con.lib.virStreamClose = this.__cjs_virStreamClose;
con.lib.virStreamRead = this.__cjs_virStreamRead;
con.lib.virStreamWrite = this.__cjs_virStreamWrite;
con.lib.virDomainGetCPUStats = this.__cjs_virDomainGetCPUStats;
con.lib.virDomainInterfaceStats = this.__cjs_virDomainInterfaceStats;
con.lib.virDomainMemoryStats = this.__cjs_virDomainMemoryStats;
con.lib.virDomainBlockStats = this.__cjs_virDomainBlockStats;
con.lib.virDomainSnapshotCreate = this.__cjs_virDomainSnapshotCreate;
con.lib.virDomain = this.__cjs_virDomain;
con.lib.virDomainHasCurrentSnapshot = this.__cjs_virDomainHasCurrentSnapshot;
con.lib.virDomainSnapshotList = this.__cjs_virDomainSnapshotList;
con.lib.virDomainSnapshot = this.__cjs_virDomainSnapshot;
con.lib.virDomainRevertToSnapshot = this.__cjs_virDomainRevertToSnapshot;
con.lib.virDomainSnapshotDelete = this.__cjs_virDomainSnapshotDelete;
con.lib.virDomainSnapshotListChildren = this.__cjs_virDomainSnapshotListChildren;
con.lib.virDomainManagedSave = this.__cjs_virDomainManagedSave;
con.lib.virDomainManagedSaveRemove = this.__cjs_virDomainManagedSaveRemove;
con.lib.virDomainSave = this.__cjs_virDomainSave;
con.lib.virDomainHasManagedSaveImage = this.__cjs_virDomainHasManagedSaveImage;
con.lib.virDomainGetJobInfo = this.__cjs_virDomainGetJobInfo;
con.lib.virDomainAttachDevice = this.__cjs_virDomainAttachDevice;
con.lib.virDomainBlockJobAbort = this.__cjs_virDomainBlockJobAbort;
con.lib.virDomainMigrate = this.__cjs_virDomainMigrate;
con.lib.virConnectListStoragePools = this.__cjs_virConnectListStoragePools;
con.lib.virConnectListDefinedStoragePools = this.__cjs_virConnectListDefinedStoragePools;
con.lib.virConnectListNetworks = this.__cjs_virConnectListNetworks;
con.lib.virConnectListDefinedNetworks = this.__cjs_virConnectListDefinedNetworks;
con.lib.virNodeListDevices = this.__cjs_virNodeListDevices;
con.lib.virDebug = this.__cjs_virDebug;
