/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.net)
	con.net = { };
con.net.SOAPClientDestroy = this.__cjs_SOAPClientDestroy;
con.net.SOAPClientGetBlockmode = this.__cjs_SOAPClientGetBlockmode;
con.net.SOAPClientBlockSocket = this.__cjs_SOAPClientBlockSocket;
con.net.SOAPClientInvoke = this.__cjs_SOAPClientInvoke;
con.net.SOAPCtxGetFile = this.__cjs_SOAPCtxGetFile;
con.net.SOAPCtxNewWithMethod = this.__cjs_SOAPCtxNewWithMethod;
con.net.SOAPCtxAddFile = this.__cjs_SOAPCtxAddFile;
con.net.SOAPCtxFree = this.__cjs_SOAPCtxFree;
con.net.SOAPEnvNewWithFault = this.__cjs_SOAPEnvNewWithFault;
con.net.SOAPEnvNewWithMethod = this.__cjs_SOAPEnvNewWithMethod;
con.net.SOAPEnvNewWithResponse = this.__cjs_SOAPEnvNewWithResponse;
con.net.SOAPEnvNewFromDoc = this.__cjs_SOAPEnvNewFromDoc;
con.net.SOAPEnvNewFromBuffer = this.__cjs_SOAPEnvNewFromBuffer;
con.net.SOAPEnvNewFromStream = this.__cjs_SOAPEnvNewFromStream;
con.net.SOAPEnvAddItem = this.__cjs_SOAPEnvAddItem;
con.net.SOAPEnvAttachment = this.__cjs_SOAPEnvAttachment;
con.net.SOAPEnvPushItem = this.__cjs_SOAPEnvPushItem;
con.net.SOAPEnvPopItem = this.__cjs_SOAPEnvPopItem;
con.net.SOAPEnvFree = this.__cjs_SOAPEnvFree;
con.net.SOAPEnvGetBody = this.__cjs_SOAPEnvGetBody;
con.net.SOAPEnvGetMethod = this.__cjs_SOAPEnvGetMethod;
con.net.SOAPEnvGetFault = this.__cjs_SOAPEnvGetFault;
con.net.SOAPEnvFindUrn = this.__cjs_SOAPEnvFindUrn;
con.net.SOAPEnvFindMethodname = this.__cjs_SOAPEnvFindMethodname;
con.net.SOAPXMLDocPrint = this.__cjs_SOAPXMLDocPrint;
con.net.SOAPGetRootDoc = this.__cjs_SOAPGetRootDoc;
con.net.SOAPGetEnv = this.__cjs_SOAPGetEnv;
con.net.SOAPXMLGetChildren = this.__cjs_SOAPXMLGetChildren;
con.net.SOAPXMLGetNext = this.__cjs_SOAPXMLGetNext;
con.net.SOAPXMLGetText = this.__cjs_SOAPXMLGetText;
con.net.SOAPFaultBuild = this.__cjs_SOAPFaultBuild;
con.net.SOAPRouterNew = this.__cjs_SOAPRouterNew;
con.net.SOAPRouterFindService = this.__cjs_SOAPRouterFindService;
con.net.SOAPRouterFree = this.__cjs_SOAPRouterFree;
con.net.SOAPServerRegisterRouter = this.__cjs_SOAPServerRegisterRouter;
con.net.SOAPServerRun = this.__cjs_SOAPServerRun;
con.net.SOAPServerDestroy = this.__cjs_SOAPServerDestroy;
con.net.SOAPRouterRegisterService = this.__cjs_SOAPRouterRegisterService;
con.net.SOAPGetCurrentNode = this.__cjs_SOAPGetCurrentNode;
con.net.SOAPGetRootNode = this.__cjs_SOAPGetRootNode;
con.net.SOAPError = this.__cjs_SOAPError;
con.net.SOAPGetServiceUrn = this.__cjs_SOAPGetServiceUrn;
con.net.SOAPGetServiceMethod = this.__cjs_SOAPGetServiceMethod;
con.net.SOAPXMLGetNodeArray = this.__cjs_SOAPXMLGetNodeArray;
con.net.SOAPGetEnvArray = this.__cjs_SOAPGetEnvArray;
con.net.SOAPGetCtxArray = this.__cjs_SOAPGetCtxArray;
