/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.lib)
	con.lib = { };
if (!con.lib.virt)
	con.lib.virt = { };
con.lib.virt.virError = this.__cjs_virError;
con.lib.virt.virConnect = this.__cjs_virConnect;
con.lib.virt.virInfo = this.__cjs_virInfo;
con.lib.virt.virClose = this.__cjs_virClose;
con.lib.virt.virNumOfActiveDomains = this.__cjs_virNumOfActiveDomains;
con.lib.virt.virNumOfInactiveDomains = this.__cjs_virNumOfInactiveDomains;
con.lib.virt.virListAllDomains = this.__cjs_virListAllDomains;
con.lib.virt.virDomainOpen = this.__cjs_virDomainOpen;
con.lib.virt.virDomainOpenUUID = this.__cjs_virDomainOpenUUID;
con.lib.virt.virDomainOpenName = this.__cjs_virDomainOpenName;
con.lib.virt.virDomainDone = this.__cjs_virDomainDone;
con.lib.virt.virDomainMemoryPeek = this.__cjs_virDomainMemoryPeek;
con.lib.virt.virDomainShutdown = this.__cjs_virDomainShutdown;
con.lib.virt.virDomainSetAutostart = this.__cjs_virDomainSetAutostart;
con.lib.virt.virDomainDestroy = this.__cjs_virDomainDestroy;
con.lib.virt.virDomainSuspend = this.__cjs_virDomainSuspend;
con.lib.virt.virDomainResume = this.__cjs_virDomainResume;
con.lib.virt.virDomainUndefine = this.__cjs_virDomainUndefine;
con.lib.virt.virDomainCreate = this.__cjs_virDomainCreate;
con.lib.virt.virDomainCreateXML = this.__cjs_virDomainCreateXML;
con.lib.virt.virDomainScreenshot = this.__cjs_virDomainScreenshot;
con.lib.virt.virDomainSendKey = this.__cjs_virDomainSendKey;
con.lib.virt.virDomainOpenConsole = this.__cjs_virDomainOpenConsole;
con.lib.virt.virStreamClose = this.__cjs_virStreamClose;
con.lib.virt.virStreamRead = this.__cjs_virStreamRead;
con.lib.virt.virStreamWrite = this.__cjs_virStreamWrite;
con.lib.virt.virDomainGetCPUStats = this.__cjs_virDomainGetCPUStats;
con.lib.virt.virDomainInterfaceStats = this.__cjs_virDomainInterfaceStats;
con.lib.virt.virDomainMemoryStats = this.__cjs_virDomainMemoryStats;
con.lib.virt.virDomainBlockStats = this.__cjs_virDomainBlockStats;
con.lib.virt.virDomainSnapshotCreate = this.__cjs_virDomainSnapshotCreate;
con.lib.virt.virDomain = this.__cjs_virDomain;
con.lib.virt.virDomainHasCurrentSnapshot = this.__cjs_virDomainHasCurrentSnapshot;
con.lib.virt.virDomainSnapshotList = this.__cjs_virDomainSnapshotList;
con.lib.virt.virDomainSnapshot = this.__cjs_virDomainSnapshot;
con.lib.virt.virDomainRevertToSnapshot = this.__cjs_virDomainRevertToSnapshot;
con.lib.virt.virDomainSnapshotDelete = this.__cjs_virDomainSnapshotDelete;
con.lib.virt.virDomainSnapshotListChildren = this.__cjs_virDomainSnapshotListChildren;
con.lib.virt.virDomainManagedSave = this.__cjs_virDomainManagedSave;
con.lib.virt.virDomainManagedSaveRemove = this.__cjs_virDomainManagedSaveRemove;
con.lib.virt.virDomainSave = this.__cjs_virDomainSave;
con.lib.virt.virDomainHasManagedSaveImage = this.__cjs_virDomainHasManagedSaveImage;
con.lib.virt.virDomainGetJobInfo = this.__cjs_virDomainGetJobInfo;
con.lib.virt.virDomainAttachDevice = this.__cjs_virDomainAttachDevice;
con.lib.virt.virDomainBlockJobAbort = this.__cjs_virDomainBlockJobAbort;
con.lib.virt.virDomainMigrate = this.__cjs_virDomainMigrate;
con.lib.virt.virConnectListStoragePools = this.__cjs_virConnectListStoragePools;
con.lib.virt.virConnectListDefinedStoragePools = this.__cjs_virConnectListDefinedStoragePools;
con.lib.virt.virConnectListNetworks = this.__cjs_virConnectListNetworks;
con.lib.virt.virConnectListDefinedNetworks = this.__cjs_virConnectListDefinedNetworks;
con.lib.virt.virNodeListDevices = this.__cjs_virNodeListDevices;
con.lib.virt.virDebug = this.__cjs_virDebug;
