/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.net)
	con.net = { };
con.net.SIPPhoneCreate = this.__cjs_SIPPhoneCreate;
con.net.SIPPhoneDestroy = this.__cjs_SIPPhoneDestroy;
con.net.SIPPhoneSetPortBase = this.__cjs_SIPPhoneSetPortBase;
con.net.SIPPhoneSetSilenceDetector = this.__cjs_SIPPhoneSetSilenceDetector;
con.net.SIPPhoneSetJitter = this.__cjs_SIPPhoneSetJitter;
con.net.SIPPhoneConnect = this.__cjs_SIPPhoneConnect;
con.net.SIPPhoneCall = this.__cjs_SIPPhoneCall;
con.net.SIPPhoneHoldRetrieveCall = this.__cjs_SIPPhoneHoldRetrieveCall;
con.net.SIPPhoneHangupCurrentCall = this.__cjs_SIPPhoneHangupCurrentCall;
con.net.SIPPhoneTransfer = this.__cjs_SIPPhoneTransfer;
con.net.SIPPhoneForward = this.__cjs_SIPPhoneForward;
con.net.SIPPhoneHangupAll = this.__cjs_SIPPhoneHangupAll;
con.net.SIPPhoneAnswer = this.__cjs_SIPPhoneAnswer;
con.net.SIPPhoneReject = this.__cjs_SIPPhoneReject;
con.net.SIPPhoneSendTone = this.__cjs_SIPPhoneSendTone;
con.net.SIPPhoneAddListener = this.__cjs_SIPPhoneAddListener;
con.net.SIPPhoneRemoveListener = this.__cjs_SIPPhoneRemoveListener;
con.net.SIPPhoneUnregister = this.__cjs_SIPPhoneUnregister;
con.net.SIPPhoneGetCodecs = this.__cjs_SIPPhoneGetCodecs;
con.net.SIPPhoneSetCodecsOrder = this.__cjs_SIPPhoneSetCodecsOrder;
con.net.SIPPhoneIsRegistered = this.__cjs_SIPPhoneIsRegistered;
con.net.SIPPhoneSetSTUNServer = this.__cjs_SIPPhoneSetSTUNServer;
con.net.SIPPhoneOnEstablishedCall = this.__cjs_SIPPhoneOnEstablishedCall;
con.net.SIPPhoneOnClearedCall = this.__cjs_SIPPhoneOnClearedCall;
con.net.SIPPhoneOnUserInputString = this.__cjs_SIPPhoneOnUserInputString;
con.net.SIPPhoneOnShowIncoming = this.__cjs_SIPPhoneOnShowIncoming;
con.net.SIPPhoneOnShowOutgoing = this.__cjs_SIPPhoneOnShowOutgoing;
con.net.SIPPhoneOnMediaFrame = this.__cjs_SIPPhoneOnMediaFrame;
con.net.SIPPhoneOnAlerting = this.__cjs_SIPPhoneOnAlerting;
con.net.SIPPhoneOnOpenMediaStreamDelegate = this.__cjs_SIPPhoneOnOpenMediaStreamDelegate;
con.net.SIPPhoneOnMediaFrameRequest = this.__cjs_SIPPhoneOnMediaFrameRequest;
con.net.SIPPhoneOnConnectRequest = this.__cjs_SIPPhoneOnConnectRequest;
con.net.SIPMediaStreamRead = this.__cjs_SIPMediaStreamRead;
con.net.SIPMediaStreamWrite = this.__cjs_SIPMediaStreamWrite;
con.net.SIPMediaStreamWriteAll = this.__cjs_SIPMediaStreamWriteAll;
con.net.SIPMediaStreamClose = this.__cjs_SIPMediaStreamClose;
con.net.SIPMediaStreamNotUsed = this.__cjs_SIPMediaStreamNotUsed;
con.net.SIPMediaStreamIsSink = this.__cjs_SIPMediaStreamIsSink;
con.net.SIPMediaStreamIsOpen = this.__cjs_SIPMediaStreamIsOpen;
con.net.SIPMediaStreamIsSource = this.__cjs_SIPMediaStreamIsSource;
con.net.SIPMediaStreamIsPaused = this.__cjs_SIPMediaStreamIsPaused;
con.net.SIPMediaStreamIsSynchronous = this.__cjs_SIPMediaStreamIsSynchronous;
con.net.SIPMediaStreamFormat = this.__cjs_SIPMediaStreamFormat;
con.net.SIPMediaStreamSetDataSize = this.__cjs_SIPMediaStreamSetDataSize;
con.net.SIPMediaStreamGetDataSize = this.__cjs_SIPMediaStreamGetDataSize;
con.net.SIPMediaStreamStart = this.__cjs_SIPMediaStreamStart;
con.net.SIPMediaStreamPause = this.__cjs_SIPMediaStreamPause;
con.net.SIPPhoneSetNoMediaTimeout = this.__cjs_SIPPhoneSetNoMediaTimeout;
con.net.SIPPhoneGetNoMediaTimeout = this.__cjs_SIPPhoneGetNoMediaTimeout;
