/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.db)
	con.db = { };
con.db.MySQLInit = this.__cjs_MySQLInit;
con.db.MySQLLibraryDone = this.__cjs_MySQLLibraryDone;
con.db.MySQLLibraryInit = this.__cjs_MySQLLibraryInit;
con.db.MySQLOptions = this.__cjs_MySQLOptions;
con.db.MySQLCountParams = this.__cjs_MySQLCountParams;
con.db.MySQLPrepare = this.__cjs_MySQLPrepare;
con.db.MySQLBindParameters = this.__cjs_MySQLBindParameters;
con.db.MySQLPreparedExecute = this.__cjs_MySQLPreparedExecute;
con.db.MySQLBindStatement = this.__cjs_MySQLBindStatement;
con.db.MySQLSTMTResult = this.__cjs_MySQLSTMTResult;
con.db.MySQLFetchRow = this.__cjs_MySQLFetchRow;
con.db.MySQLConnect = this.__cjs_MySQLConnect;
con.db.MySQLDisconnect = this.__cjs_MySQLDisconnect;
con.db.MySQLAutoCommit = this.__cjs_MySQLAutoCommit;
con.db.MySQLCommit = this.__cjs_MySQLCommit;
con.db.MySQLRollback = this.__cjs_MySQLRollback;
con.db.MySQLError = this.__cjs_MySQLError;
con.db.MySQLSTMTError = this.__cjs_MySQLSTMTError;
con.db.MySQLWarningCount = this.__cjs_MySQLWarningCount;
con.db.MySQLListTables = this.__cjs_MySQLListTables;
con.db.MySQLListColumns = this.__cjs_MySQLListColumns;
con.db.MySQLListDatabases = this.__cjs_MySQLListDatabases;
con.db.MySQLFreeResult = this.__cjs_MySQLFreeResult;
con.db.MySQLFetchForward = this.__cjs_MySQLFetchForward;
con.db.MySQLCountColumns = this.__cjs_MySQLCountColumns;
con.db.MySQLCountRows = this.__cjs_MySQLCountRows;
con.db.MySQLDescribeCol = this.__cjs_MySQLDescribeCol;
con.db.MySQLDescribeCol2 = this.__cjs_MySQLDescribeCol2;
con.db.MySQLStatement = this.__cjs_MySQLStatement;
con.db.MySQLFreeQuery = this.__cjs_MySQLFreeQuery;
con.db.MySQLExecute = this.__cjs_MySQLExecute;
con.db.MySQLQuery = this.__cjs_MySQLQuery;
con.db.MySQLStoreResult = this.__cjs_MySQLStoreResult;
con.db.MySQLUseResult = this.__cjs_MySQLUseResult;
con.db.MySQLFetchAbsolute = this.__cjs_MySQLFetchAbsolute;
con.db.MySQLFetchFirst = this.__cjs_MySQLFetchFirst;
con.db.MySQLFetchNext = this.__cjs_MySQLFetchNext;
con.db.MySQLFetchLast = this.__cjs_MySQLFetchLast;
con.db.MySQLColumnGet = this.__cjs_MySQLColumnGet;
con.db.MySQLSTMTColumnGet = this.__cjs_MySQLSTMTColumnGet;
con.db.MySQLEscape = this.__cjs_MySQLEscape;
con.db.MySQLFD = this.__cjs_MySQLFD;
con.db.MySQLSendQuery = this.__cjs_MySQLSendQuery;
con.db.MySQLReadQueryResult = this.__cjs_MySQLReadQueryResult;
con.db.MySQLPosition = this.__cjs_MySQLPosition;
