/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.net)
	con.net = { };
con.net.Twitter_Create = this.__cjs_Twitter_Create;
con.net.Twitter_Destroy = this.__cjs_Twitter_Destroy;
con.net.Twitter_Auth = this.__cjs_Twitter_Auth;
con.net.Twitter_getTwitterUsername = this.__cjs_Twitter_getTwitterUsername;
con.net.Twitter_getTwitterPassword = this.__cjs_Twitter_getTwitterPassword;
con.net.Twitter_setTwitterUsername = this.__cjs_Twitter_setTwitterUsername;
con.net.Twitter_setTwitterPassword = this.__cjs_Twitter_setTwitterPassword;
con.net.Twitter_search = this.__cjs_Twitter_search;
con.net.Twitter_statusUpdate = this.__cjs_Twitter_statusUpdate;
con.net.Twitter_statusShowById = this.__cjs_Twitter_statusShowById;
con.net.Twitter_statusDestroyById = this.__cjs_Twitter_statusDestroyById;
con.net.Twitter_timelinePublicGet = this.__cjs_Twitter_timelinePublicGet;
con.net.Twitter_timelineFriendsGet = this.__cjs_Twitter_timelineFriendsGet;
con.net.Twitter_timelineUserGet = this.__cjs_Twitter_timelineUserGet;
con.net.Twitter_featuredUsersGet = this.__cjs_Twitter_featuredUsersGet;
con.net.Twitter_mentionsGet = this.__cjs_Twitter_mentionsGet;
con.net.Twitter_userGet = this.__cjs_Twitter_userGet;
con.net.Twitter_friendsGet = this.__cjs_Twitter_friendsGet;
con.net.Twitter_followersGet = this.__cjs_Twitter_followersGet;
con.net.Twitter_directMessageGet = this.__cjs_Twitter_directMessageGet;
con.net.Twitter_directMessageSend = this.__cjs_Twitter_directMessageSend;
con.net.Twitter_directMessageGetSent = this.__cjs_Twitter_directMessageGetSent;
con.net.Twitter_directMessageDestroyById = this.__cjs_Twitter_directMessageDestroyById;
con.net.Twitter_friendshipCreate = this.__cjs_Twitter_friendshipCreate;
con.net.Twitter_friendshipDestroy = this.__cjs_Twitter_friendshipDestroy;
con.net.Twitter_friendshipShow = this.__cjs_Twitter_friendshipShow;
con.net.Twitter_friendsIdsGet = this.__cjs_Twitter_friendsIdsGet;
con.net.Twitter_followersIdsGet = this.__cjs_Twitter_followersIdsGet;
con.net.Twitter_accountRateLimitGet = this.__cjs_Twitter_accountRateLimitGet;
con.net.Twitter_favoriteGet = this.__cjs_Twitter_favoriteGet;
con.net.Twitter_favoriteCreate = this.__cjs_Twitter_favoriteCreate;
con.net.Twitter_favoriteDestroy = this.__cjs_Twitter_favoriteDestroy;
con.net.Twitter_blockCreate = this.__cjs_Twitter_blockCreate;
con.net.Twitter_blockDestroy = this.__cjs_Twitter_blockDestroy;
con.net.Twitter_savedSearchGet = this.__cjs_Twitter_savedSearchGet;
con.net.Twitter_savedSearchCreate = this.__cjs_Twitter_savedSearchCreate;
con.net.Twitter_savedSearchShow = this.__cjs_Twitter_savedSearchShow;
con.net.Twitter_savedSearchDestroy = this.__cjs_Twitter_savedSearchDestroy;
con.net.Twitter_isCurlInit = this.__cjs_Twitter_isCurlInit;
con.net.Twitter_getLastCurlError = this.__cjs_Twitter_getLastCurlError;
con.net.Twitter_getLastWebResponse = this.__cjs_Twitter_getLastWebResponse;
con.net.Twitter_getProxyServerIp = this.__cjs_Twitter_getProxyServerIp;
con.net.Twitter_getProxyServerPort = this.__cjs_Twitter_getProxyServerPort;
con.net.Twitter_getProxyUserName = this.__cjs_Twitter_getProxyUserName;
con.net.Twitter_getProxyPassword = this.__cjs_Twitter_getProxyPassword;
con.net.Twitter_setProxyServerIp = this.__cjs_Twitter_setProxyServerIp;
con.net.Twitter_setProxyServerPort = this.__cjs_Twitter_setProxyServerPort;
con.net.Twitter_setProxyUserName = this.__cjs_Twitter_setProxyUserName;
con.net.Twitter_setProxyPassword = this.__cjs_Twitter_setProxyPassword;
