/* This file is generated automatically by generatejs.con. Do not edit. */

'use strict';

if (!con.db)
	con.db = { };
con.db.NuoSetAutoCommit = this.__cjs_NuoSetAutoCommit;
con.db.NuoGetAutoCommit = this.__cjs_NuoGetAutoCommit;
con.db.NuoSetIsolationLevel = this.__cjs_NuoSetIsolationLevel;
con.db.NuoGetIsolationLevel = this.__cjs_NuoGetIsolationLevel;
con.db.NuoInfo = this.__cjs_NuoInfo;
con.db.NuoPrepareTransaction = this.__cjs_NuoPrepareTransaction;
con.db.NuoRollback = this.__cjs_NuoRollback;
con.db.NuoCommit = this.__cjs_NuoCommit;
con.db.NuoConnect = this.__cjs_NuoConnect;
con.db.NuoConnectCreate = this.__cjs_NuoConnectCreate;
con.db.NuoDisconnect = this.__cjs_NuoDisconnect;
con.db.NuoQuery = this.__cjs_NuoQuery;
con.db.NuoNonQuery = this.__cjs_NuoNonQuery;
con.db.NuoError = this.__cjs_NuoError;
con.db.NuoFreeResult = this.__cjs_NuoFreeResult;
con.db.NuoSetCursorName = this.__cjs_NuoSetCursorName;
con.db.NuoSetNull = this.__cjs_NuoSetNull;
con.db.NuoSetBlob = this.__cjs_NuoSetBlob;
con.db.NuoSetClob = this.__cjs_NuoSetClob;
con.db.NuoBlobCreate = this.__cjs_NuoBlobCreate;
con.db.NuoClobCreate = this.__cjs_NuoClobCreate;
con.db.NuoBlobWrite = this.__cjs_NuoBlobWrite;
con.db.NuoClobWrite = this.__cjs_NuoClobWrite;
con.db.NuoPrepared = this.__cjs_NuoPrepared;
con.db.NuoSetParameter = this.__cjs_NuoSetParameter;
con.db.NuoExecute = this.__cjs_NuoExecute;
con.db.NuoFinish = this.__cjs_NuoFinish;
con.db.NuoParameterCount = this.__cjs_NuoParameterCount;
con.db.NuoParameterMeta = this.__cjs_NuoParameterMeta;
con.db.NuoAnalyze = this.__cjs_NuoAnalyze;
con.db.NuoCountRows = this.__cjs_NuoCountRows;
con.db.NuoCountColumns = this.__cjs_NuoCountColumns;
con.db.NuoColumnInfo = this.__cjs_NuoColumnInfo;
con.db.NuoValues = this.__cjs_NuoValues;
con.db.NuoValue = this.__cjs_NuoValue;
con.db.NuoValueByName = this.__cjs_NuoValueByName;
con.db.NuoBlob = this.__cjs_NuoBlob;
con.db.NuoBlobByName = this.__cjs_NuoBlobByName;
con.db.NuoClob = this.__cjs_NuoClob;
con.db.NuoClobByName = this.__cjs_NuoClobByName;
con.db.NuoFirst = this.__cjs_NuoFirst;
con.db.NuoNext = this.__cjs_NuoNext;
con.db.NuoPrevious = this.__cjs_NuoPrevious;
con.db.NuoLast = this.__cjs_NuoLast;
con.db.NuoRefresh = this.__cjs_NuoRefresh;
con.db.NuoAbsolute = this.__cjs_NuoAbsolute;
