#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
    CONCEPT_FUNCTION(M2TSDemux)
    CONCEPT_FUNCTION(M2TSSyncOffset)
    CONCEPT_FUNCTION(M2TSPeek)
    CONCEPT_FUNCTION(M2TSChpid)
    CONCEPT_FUNCTION(M2TSChcont)
    CONCEPT_FUNCTION(M2TSPTS);
    CONCEPT_FUNCTION(M2TSPacket)
    CONCEPT_FUNCTION(M2TSTable);
}
#endif // __LIBRARY_H
