#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(__profile)
CONCEPT_FUNCTION(ProfilerDelegate)
CONCEPT_FUNCTION(CoreMemoryInfo)
CONCEPT_FUNCTION(ProfilerReset)
}
#endif // __LIBRARY_H
