#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT MANAGEMENT_PARAMETERS;

// other functions declared here
CONCEPT_DLL_API CONCEPT__clock        CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__microseconds CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__asctime      CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__ctime        CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__difftime     CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__localtime    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__gmtime       CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__time         CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__mktime       CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__slocaltime   CONCEPT_API_PARAMETERS;

CONCEPT_FUNCTION(setlocale)
CONCEPT_FUNCTION(localeconv)

CONCEPT_FUNCTION(strftime)
CONCEPT_FUNCTION(strftime2)

CONCEPT_FUNCTION(strptime)
CONCEPT_FUNCTION(strptime2)
}
#endif // __LIBRARY_H
