#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
    CONCEPT_DLL_API ON_CREATE_CONTEXT MANAGEMENT_PARAMETERS;
    CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;
    CONCEPT_FUNCTION(stem)
    CONCEPT_FUNCTION(extractWords)
    CONCEPT_FUNCTION(stemmer_new)
    CONCEPT_FUNCTION(stemmer_stem)
    CONCEPT_FUNCTION(stemmer_delete)
}
#endif // __LIBRARY_H
