#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(InitMBR)
CONCEPT_FUNCTION(CloseMBR)
CONCEPT_FUNCTION(ResetMBR)
CONCEPT_FUNCTION(WriteMBR)
CONCEPT_FUNCTION(ReadMBR)
CONCEPT_FUNCTION(SetFreqMBR)
CONCEPT_FUNCTION(GetFreqMBR)
CONCEPT_FUNCTION(SetVolumeRatioMBR)
CONCEPT_FUNCTION(GetVolumeRatioMBR)
CONCEPT_FUNCTION(FlushMBR)
CONCEPT_FUNCTION(LastErrorMBR)
CONCEPT_FUNCTION(LastErrorStrMBR)
}
#endif // __LIBRARY_H
