#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_DLL_API CONCEPT_FtpConnect      CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpLogin        CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpQuit         CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpOptions      CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpSite         CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpLastResponse CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpSysType      CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpSize         CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpModDate      CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpChdir        CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpMkdir        CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpRmdir        CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpNlst         CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpDir          CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpCDUp         CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpPwd          CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpGet          CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpPut          CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpDelete       CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpRename       CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpAccess       CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpClose        CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpRead         CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_FtpWrite        CONCEPT_API_PARAMETERS;
}
#endif // __LIBRARY_H
