#ifndef __LIBRARY_H
#define __LIBRARY_H

#include "stdlibrary.h"

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(H265Encoder)
CONCEPT_FUNCTION(H265Decoder)
CONCEPT_FUNCTION(H265EncoderSet)
CONCEPT_FUNCTION(H265DecoderSet)
CONCEPT_FUNCTION(H265EncoderGet)
CONCEPT_FUNCTION(H265DecoderGet)
CONCEPT_FUNCTION(H265Encode)
CONCEPT_FUNCTION(H265Decode)
CONCEPT_FUNCTION(H265EncoderDone)
CONCEPT_FUNCTION(H265DecoderDone)
}
#endif // __LIBRARY_H
