#include "stdlibrary.h"

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT MANAGEMENT_PARAMETERS;

CONCEPT_FUNCTION(PDFLoadBuffer)
CONCEPT_FUNCTION(PDFLoad)
CONCEPT_FUNCTION(PDFClose)
CONCEPT_FUNCTION(PDFPageCount)
CONCEPT_FUNCTION(PDFPageText)
CONCEPT_FUNCTION(PDFFindText)
CONCEPT_FUNCTION(PDFPageImageBuffer)
CONCEPT_FUNCTION(PDFPageImage)

CONCEPT_FUNCTION(PDFAttachments)
}
