#ifndef __LIBRARY_H
#define __LIBRARY_H

// user definition ...

extern "C" {
CONCEPT_DLL_API ON_CREATE_CONTEXT  MANAGEMENT_PARAMETERS;
CONCEPT_DLL_API ON_DESTROY_CONTEXT MANAGEMENT_PARAMETERS;

//CONCEPT_DLL_API CONCEPT_mail_login CONCEPT_API_PARAMETERS;

// other functions declared here
CONCEPT_DLL_API CONCEPT_mail       CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_newsletter CONCEPT_API_PARAMETERS;

CONCEPT_DLL_API CONCEPT_mail_error CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT_sent_count CONCEPT_API_PARAMETERS;


CONCEPT_DLL_API CONCEPT__pop3_open           CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__pop3_open_secured   CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__pop3_count_messages CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__pop3_get_message    CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__pop3_delete_message CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__pop3_close          CONCEPT_API_PARAMETERS;
CONCEPT_DLL_API CONCEPT__pop3_error          CONCEPT_API_PARAMETERS;
}
#endif // __LIBRARY_H
